name: project_noteapp
description: Your app description
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 4.14.0
  firebase_core: 2.24.2
  firebase_auth: 4.16.0
  intl: 0.19.0
  flutter_signin_button: 2.0.0
  cached_network_image: 3.3.1  # Replace with the version you want

dev_dependencies:
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/cat.png
    - assets/user.png
